version: 2
jobs:
  build:
    machine: true
    working_directory: ~/universal-link-validator
    environment:
      BRANCH_STACK: node
      DC2: true
    steps:
    - checkout
    - run:
        name: Clone Deploy
        command: cd && git clone https://github.com/BranchMetrics/deploy.git
    - run:
        name: Run Build Script
        command: ~/deploy/docker/build.sh
    - run:
        name: Run Tests
        command: echo "No tests == No Fails"
    - run: mkdir -p workspace && cp -R ~/docker-build workspace/
    - persist_to_workspace:
        root: workspace
        paths:
          - docker-build
  deploy:
    machine: true
    working_directory: ~/universal-link-validator
    environment:
      DC2: true
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - run: cp -R /tmp/workspace/docker-build ~/
    - run:
        name: Clone Deploy Repo
        command: git clone https://github.com/BranchMetrics/deploy.git ~/deploy
    - run:
        name: Run Deploy Script
        command: ~/deploy/docker/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: [master,production]
